CREATE VIEW PRESENTATION_VIEW AS
    SELECT
        COMPANY.NAME AS BOOKED_COMPANY,
        ROOM.ROOM_ID AS BOOKED_ROOM_NUMBER,
        ROOM.FLOOR_NUMBER AS FLOOR,
        ROOM.SEAT_CAPACITY AS SEATS,
        START_TIME,
        END_TIME

    FROM PRESENTATION

    INNER JOIN COMPANY
    ON COMPANY.COMPANY_ID = PRESENTATION.BOOKED_COMPANY_ID

    INNER JOIN ROOM
    ON ROOM.ROOM_ID = PRESENTATION.BOOKED_ROOM_ID;